<?php
/**
 * TL_ROOT/system/modules/backend_websitepreview/languages/ru/modules.php 
 * 
 * Contao extension: backend_websitepreview 0.0.1 alpha1 
 * Russian translation file 
 * 
 * Copyright : &copy; 2010-2011 DyaGa
 * License   : LGPL 
 * Author    : Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * Translator: Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['backend_websitepreview'] = array('Просмотр сайта в новом окне', 'Добавляет ссылку предосмотра сайта в заголовок административной части. Ссылка позволяет открывать сайт в новом окне без использования стандартного модуля предосмотра.');

?>
